apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-catalog-cm
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.catalog | indent 2 }}
