apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config-cm
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  bootstrap.sh: |-
    #!/bin/bash

    cd /root/bootstrap

    mkdir -p $PRESTO_HOME/etc/catalog

    cat ./node.properties > $PRESTO_HOME/etc/node.properties
    cat ./jvm.config > $PRESTO_HOME/etc/jvm.config
    cat ./config.properties > $PRESTO_HOME/etc/config.properties
    cat ./log.properties > $PRESTO_HOME/etc/log.properties

    sed -i 's/${COORDINATOR_NODE}/'$COORDINATOR_NODE'/g' $PRESTO_HOME/etc/config.properties

    for cfg in ../catalog/*; do
      cat $cfg > $PRESTO_HOME/etc/catalog/${cfg##*/}
    done

    $PRESTO_HOME/bin/launcher run --verbose
  node.properties: |-
    node.environment={{ .Values.node.environment }}
    node.data-dir={{ .Values.node.dataDir }}
  jvm.config: |-
    -server
    -Xmx{{ .Values.jvm.maxHeapSize }}
    -XX:{{ .Values.jvm.GCMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.jvm.GCMethod.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
  config.properties: |-
    coordinator=${COORDINATOR_NODE}
    node-scheduler.include-coordinator={{ .Values.config.includeCoordinator }}
    http-server.http.port={{ .Values.config.httpPort }}
    query.max-memory={{ .Values.config.maxMemory }}
    query.max-memory-per-node={{ .Values.config.maxMemoryPerNode }}
    query.max-total-memory-per-node={{ .Values.config.maxTotalMemoryPerNode }}
    discovery-server.enabled=true
    discovery.uri=http://{{ template "fullname" . }}-coordinator-service:{{ .Values.config.httpPort }}
  log.properties: |-
    com.facebook.presto={{ .Values.log.level }}
