kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-coordinator-service
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
    - port: {{ .Values.config.httpPort }}
      name: http-coord
  selector:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: coordinator
  type: {{ .Values.coordinator.service.type }}
