apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    helm.sh/chart: {{ include "grafana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  grafana-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
