apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-metastore-secret
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  database-dba-password: {{ .Values.hive.metastore.DBAPassword | b64enc | quote }}
  database-user-password: {{ .Values.hive.metastore.password | b64enc | quote }}
