apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-metastore-init-cm
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  execute.sql: |-
{{- if eq .Values.hive.metastore.type "mysql" }}
    -- create database
    CREATE DATABASE metastore DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    -- create user and grant authorization
    GRANT ALL ON metastore.* TO 'hive'@'%' IDENTIFIED BY '${IDENTIFIED}';
{{- else if eq .Values.hive.metastore.type "mysql" }}
    -- create user
    create user hive identified by "${IDENTIFIED}";
    -- grant authorization
    grant dba to hive;
{{- end }}
