apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "filebeat.name" . }}-config
    helm.sh/chart: {{ include "filebeat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false

    processors:
      - add_cloud_metadata:

    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}

    output.logstash:
      hosts: ["{{ .Values.logstash.host }}:{{ .Values.logstash.port }}"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-prospector
  labels:
    app.kubernetes.io/name: {{ include "filebeat.name" . }}-prospector
    helm.sh/chart: {{ include "filebeat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
        - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
        - drop_fields:
            when:
              has_fields: ['kubernetes.labels.app']
            fields:
              - 'kubernetes.labels.app'
