apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "filebeat.name" . }}
    helm.sh/chart: {{ include "filebeat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "filebeat.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "filebeat.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "filebeat.fullname" . }}
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/filebeat.yml"
            - "-e"
          env:
            - name: ELASTICSEARCH_HOST
              value: "{{ .Values.elasticsearch.host }}"
            - name: ELASTICSEARCH_PORT
              value: "{{ .Values.elasticsearch.port }}"
            - name: ELASTICSEARCH_USERNAME
              value: elastic
            - name: ELASTICSEARCH_PASSWORD
              value: changeme
            - name: ELASTIC_CLOUD_ID
              value: ""
            - name: ELASTIC_CLOUD_AUTH
              value: ""
            - name: "XPACK_MONITORING_ENABLED"
              value: "true"
            - name: "XPACK_MONITORING_ELASTICSEARCH_URL"
              value: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
            - name: "XPACK_MONITORING_ELASTICSEARCH_HOSTS"
              value: "http://{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"
          ports:
            - name: monitor
              containerPort: 9200
              protocol: TCP
            - name: data
              containerPort: 5066
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: prospectors
              mountPath: /usr/share/filebeat/prospectors.d
              readOnly: true
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
          securityContext:
            runAsUser: 0
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: {{ include "filebeat.fullname" . }}-config
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: prospectors
          configMap:
            defaultMode: 0600
            name: {{ include "filebeat.fullname" . }}-prospector
        - name: data
        {{- if .Values.persistence.enable }}
          persistentVolumeClaim:
            claimName: {{ include "filebeat.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
