{{ if .Values.persistence.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "filebeat.name" . }}
    helm.sh/chart: {{ include "filebeat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
