# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 192.168.101.88:5000/elasticsearch/elasticsearch
  tag: 6.4.3
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  discovery:
    port: 9300
    type: ClusterIP
  data:
    port: 9200
    type: ClusterIP

master:
  replicaCount: 3
data:
  persistence:
    enable: false
    storageClass: vsphere-volume-sc
    size: 50Gi
  replicaCount: 3

history:
  enable: true
  image:
    repository: 192.168.101.88:5000/busybox
    tag: 1.29.3
    pullPolicy: IfNotPresent
  schedule: "0 1 * * *"
  retention: 5

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - elasticsearch.kube.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
