apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "logstash.name" . }}
    helm.sh/chart: {{ include "logstash.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
      }
    }

    #filter {
    #  mutate {
    #    remove_field => [ "app", "kubernetes.labels.app" ]
    #  }
    #}

    output {
      elasticsearch {
        hosts => ["{{ .Values.elasticsearch.host }}:{{ .Values.elasticsearch.port }}"]
        manage_template => false
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
        document_type => "%{[@metadata][type]}"
      }
    }
