apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-zookeeper-config
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-zookeeper-config
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  bootstrap.sh: |-
    #!/bin/bash
    
    # Get this node's FQDN
    FQDN=`nslookup $HOSTNAME 2> /dev/null | grep "Address 1:" | awk '{print $4}'`
    
    # Set this node's ZOOKEEP_MY_ID
    ZOO_MY_ID=$((${HOSTNAME##*-} + 1))
    
    for i in {1..3}
    do
    	if [[ "$i" == "$ZOO_MY_ID" ]]; then
    		ZOO_SERVERS="$ZOO_SERVERS server.$i=0.0.0.0:2888:3888"
    	else
    		ZOO_SERVERS="$ZOO_SERVERS server.$i=${HOSTNAME%-*}-$(($i - 1)).${FQDN#*.}:2888:3888"
    	fi
    done
    
    export ZOO_MY_ID
    export ZOO_SERVERS

    echo $ZOO_MY_ID
    echo $ZOO_SERVERS

    mkdir -p /zookeeper/{data,datalog,logs}
    
    /docker-entrypoint.sh zkServer.sh start-foreground
