apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
      app.kubernetes.io/instance: {{ .Release.Name }}
      app-role: hive-metastore
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
        app.kubernetes.io/instance: {{ .Release.Name }}
        app-role: hive-metastore
    spec:
      containers:
        - name: hive-metastore
          image: {{ .Values.hive.metastore.image.repository }}:{{ .Values.hive.metastore.image.tag }}
          imagePullPolicy: {{ .Values.hive.metastore.image.pullPolicy }}
          env:
            - name: SYSDBA_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
                  key: database-dba-password
            - name: BUFFER
              value: "2048"
            - name: MAX_BUFFER
              value: "65536"
            - name: DM7_INSTANCE_NAME
              value: "hive_metastore"
            - name: DM7_DEM_FLAG
              value: "true"
          ports:
            - name: dem
              containerPort: 8080
              protocol: TCP
            - name: data
              containerPort: 5236
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /opt/dmdbms/data
            - name: key
              mountPath: /opt/dmdbms/bin/dm.key
              subPath: dm.key
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: 5236
            initialDelaySeconds: 60
            timeoutSeconds: 2
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 5236
            initialDelaySeconds: 20
            timeoutSeconds: 2
      volumes:
        - name: data
{{- if .Values.hive.metastore.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
{{- else }}
          emptyDir: {}
{{- end }}
        - name: key
          secret:
            secretName: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
            items:
              - key: dm.key
                path: dm.key
