apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-presto-worker
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-worker
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.presto.worker.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
      app-role: presto-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
        app-role: presto-worker
    spec:
      initContainers:
        - name: wait-coordinator
          image: {{ .Values.presto.image.repository }}:{{ .Values.presto.image.tag }}
          imagePullPolicy: {{ .Values.presto.image.pullPolicy }}
          command: ["bash", "-c", "until curl -sf http://{{ include "dmcop-bigdata.fullname" . }}-presto-coordinator.{{ .Release.Namespace }}:8080/ui/; do echo 'waiting for coordinator started...'; sleep 2; done;"]
      containers:
        - name: presto-worker
          image: {{ .Values.presto.image.repository }}:{{ .Values.presto.image.tag }}
          imagePullPolicy: {{ .Values.presto.image.pullPolicy }}
          command: ["bash", "-c", "cat /root/bootstrap/bootstrap.sh | bash"]
          env:
            - name: COORDINATOR_NODE
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: presto-config-volume
              mountPath: /root/bootstrap
            - name: presto-catalog-volume
              mountPath: /root/catalog
            - name: presto-data-volume
              mountPath: /var/presto/data
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - curl -s http://{{ include "dmcop-bigdata.fullname" . }}-presto-coordinator.{{ .Release.Namespace }}:8080/v1/node | tr ',' '\n' | grep -s $(hostname -i)
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
      volumes:
        - name: presto-config-volume
          configMap:
            name: {{ include "dmcop-bigdata.fullname" . }}-presto-config
        - name: presto-catalog-volume
          configMap:
            name: {{ include "dmcop-bigdata.fullname" . }}-presto-catalog
        - name: presto-data-volume
          emptyDir: {}
