{{ if .Values.hive.metastore.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.hive.metastore.persistence.size }}
  storageClassName: {{ .Values.hive.metastore.persistence.storageClass }}
{{- end }}
