apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hadoop-config
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hadoop-config
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.hadoop.config.storageClass }}
