apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  database-dba-password: {{ randAlphaNum 10 | b64enc | quote }}
  database-hive-password: {{ randAlphaNum 10 | b64enc | quote }}
  dm.key: {{ .Values.hive.metastore.license }}
