apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-zookeeper
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-zookeeper
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 2181
      targetPort: client
      protocol: TCP
      name: client
    - port: 2888
      targetPort: leader
      protocol: TCP
      name: leader
    - port: 3888
      targetPort: election
      protocol: TCP
      name: election
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-zookeeper
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: zookeeper
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-zookeeper-cluster
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-zookeeper-cluster
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.zookeeper.service.type }}
  ports:
    - port: 2181
      targetPort: client
      protocol: TCP
      name: client
    - port: 2888
      targetPort: leader
      protocol: TCP
      name: leader
    - port: 3888
      targetPort: election
      protocol: TCP
      name: election
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-zookeeper-cluster
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: zookeeper
