apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-presto-coordinator
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-coordinator
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.presto.coordinator.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-coordinator
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: presto-coordinator
