apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hive-metastore
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.hive.metastore.service.type }}
  ports:
    - port: 5236
      targetPort: data
      protocol: TCP
      name: data
    - port: 8080
      targetPort: dem
      protocol: TCP
      name: dem
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive-metastore
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: hive-metastore
