apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-presto-worker
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-worker
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.presto.worker.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-presto-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: presto-worker
