apiVersion: v1
kind: Service
metadata:
  name: {{ include "dmcop-bigdata.fullname" . }}-hive
  labels:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive
    helm.sh/chart: {{ include "dmcop-bigdata.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.hive.service.type }}
  ports:
    - port: 10000 
      targetPort: hive
      protocol: TCP
      name: hive
    - port: 10002
      targetPort: ui
      protocol: TCP
      name: ui
    - port: 9083
      targetPort: metastore
      protocol: TCP
      name: metastore
  selector:
    app.kubernetes.io/name: {{ include "dmcop-bigdata.name" . }}-hive
    app.kubernetes.io/instance: {{ .Release.Name }}
    app-role: hive
